export const LOGIN_SUCCESS      = 'LOGIN_SUCCESS'
export const LOGIN_FAIL         = 'LOGIN_FAIL'
export const REGISTER_SUCCESS   = 'REGISTER_SUCCESS'
export const REGISTER_FAIL      = 'REGISTER_FAIL'
export const SEND_OTP_SUCCESS   = 'SEND_OTP_SUCCESS'
export const SEND_OTP_FAIL      = 'SEND_OTP_FAIL'
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS'
export const VERIFY_OTP_FAIL    = 'VERIFY_OTP_FAIL'